(defpackage nndescent/tests
  (:use #:cl #:fiveam)
  (:local-nicknames (#:m  #:nndescent/metrics)
                    (#:q  #:nndescent/pqueue)
                    (#:g  #:nndescent/generation)
                    (#:rt #:nndescent/random-tree)
                    (#:rf #:nndescent/random-forest)
                    (#:n  #:nndescent/naive)
                    (#:nn #:nndescent/nndescent)
                    (#:vs #:vector-sum)
                    (#:a  #:approx))
  (:export #:run-tests #:run-tests-ci))
