(defpackage nndescent/point
  (:use #:cl)
  (:shadow #:plusp)
  (:export #:plusp #:op #:dist #:euclidean-dist))
(in-package :nndescent/point)

(deftype dist ()
  '(function ((simple-array single-float (*))
              (simple-array single-float (*)))
    (values (single-float 0f0) &optional)))

(serapeum:-> plusp ((simple-array single-float (*))
                    (simple-array single-float (*))
                    (simple-array single-float (*)))
             (values boolean &optional))
(defun plusp (p p1 p2)
  (declare (optimize (speed 3)))
  (let ((n (length p)))
    (assert (= n (length p1) (length p2)))
    (cl:plusp
     (loop for i below n
           for %p  = (aref p  i)
           for %p1 = (aref p1 i)
           for %p2 = (aref p2 i)
           sum (* (- %p (/ (+ %p1 %p2) 2))
                  (- %p1 %p2))
           single-float))))

(serapeum:-> op ((simple-array single-float (*))
                 (simple-array single-float (*))
                 real real)
             (values (simple-array single-float (*)) &optional))
(defun op (p1 p2 s1 s2)
  (declare (optimize (speed 3)))
  (let ((n (length p1)))
    (assert (= n (length p2)))
    (let ((res (make-array n :element-type 'single-float))
          (s1 (float s1 0f0))
          (s2 (float s2 0f0)))
      (loop for i below (length res) do
        (setf (aref res i)
              (+ (* s1 (aref p1 i))
                 (* s2 (aref p2 i)))))
      res)))

(serapeum:-> euclidean-dist ((simple-array single-float (*))
                             (simple-array single-float (*)))
             (values (single-float 0f0) &optional))
(defun euclidean-dist (p1 p2)
  (declare (optimize (speed 3)))
  (let ((n (length p1)))
    (assert (= n (length p2)))
    (sqrt
     (loop for i below n
           sum (expt (- (aref p1 i) (aref p2 i)) 2)
           single-float))))
